apiVersion: v1
entries:
  phpmyadmin:
  - apiVersion: v2
    appVersion: v2024.4.3
    created: "2024-04-03T12:30:09.11497982+06:00"
    description: phpMyAdmin Helm chart for Kubernetes
    digest: d7b3ba8ca7a2bd2ccf1767b3221e2e257136f8e0dfa832f78985b8708cf105d9
    home: https://www.phpmyadmin.net
    icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
    maintainers:
    - email: tasdid@appscode.com
      name: tasdid
    name: phpmyadmin
    type: application
    urls:
    - phpmyadmin-v2024.4.3.tgz
    version: v2024.4.3
generated: "2024-04-03T12:30:09.106394521+06:00"
