apiVersion: v2
name: phpmyadmin
description: phpMyAdmin Helm chart for Kubernetes
type: application
version: v2024.4.3
appVersion: v2024.4.3
home: https://www.phpmyadmin.net
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
maintainers:
- name: tasdid
  email: tasdid@appscode.com
